# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import centralstorage_pb2 as centralstorage__pb2


class CentralStorageServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
                '/central.CentralStorageService/Register',
                request_serializer=centralstorage__pb2.RegisterRequest.SerializeToString,
                response_deserializer=centralstorage__pb2.ConfirmationResponse.FromString,
                )
        self.Map = channel.unary_unary(
                '/central.CentralStorageService/Map',
                request_serializer=centralstorage__pb2.KeyRequest.SerializeToString,
                response_deserializer=centralstorage__pb2.HostResponse.FromString,
                )
        self.Terminate = channel.unary_unary(
                '/central.CentralStorageService/Terminate',
                request_serializer=centralstorage__pb2.EmptyRequest.SerializeToString,
                response_deserializer=centralstorage__pb2.ConfirmationResponse.FromString,
                )


class CentralStorageServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Register(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Map(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Terminate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CentralStorageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=centralstorage__pb2.RegisterRequest.FromString,
                    response_serializer=centralstorage__pb2.ConfirmationResponse.SerializeToString,
            ),
            'Map': grpc.unary_unary_rpc_method_handler(
                    servicer.Map,
                    request_deserializer=centralstorage__pb2.KeyRequest.FromString,
                    response_serializer=centralstorage__pb2.HostResponse.SerializeToString,
            ),
            'Terminate': grpc.unary_unary_rpc_method_handler(
                    servicer.Terminate,
                    request_deserializer=centralstorage__pb2.EmptyRequest.FromString,
                    response_serializer=centralstorage__pb2.ConfirmationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'central.CentralStorageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CentralStorageService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/central.CentralStorageService/Register',
            centralstorage__pb2.RegisterRequest.SerializeToString,
            centralstorage__pb2.ConfirmationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Map(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/central.CentralStorageService/Map',
            centralstorage__pb2.KeyRequest.SerializeToString,
            centralstorage__pb2.HostResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Terminate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/central.CentralStorageService/Terminate',
            centralstorage__pb2.EmptyRequest.SerializeToString,
            centralstorage__pb2.ConfirmationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
